# =================================================================
# CONFIGURAZIONE DEL DATA SOURCE PRINCIPALE (ASSO)
# =================================================================
spring.datasource.tenants.asso.url=jdbc:mysql://localhost:3306/asso?useSSL=false&serverTimezone=UTC
spring.datasource.tenants.asso.username=asso
spring.datasource.tenants.asso.password=assocs
spring.datasource.tenants.asso.driver-class-name=com.mysql.cj.jdbc.Driver

# PARAMETRI HIKARI GENERALI
# Spring Boot gestisce automaticamente i parametri come maximumPoolSize e idleTimeout
# ma possiamo sovrascriverli se necessario.
spring.datasource.asso.hikari.maximum-pool-size = 5
spring.datasource.asso.hikari.idle-timeout = 30000

# =================================================================
# ALTRI DATA SOURCE (DEMO E MARIANO)
# =================================================================
spring.datasource.tenants.demo.url=jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
spring.datasource.tenants.demo.username=demo
spring.datasource.tenants.demo.password=democs
spring.datasource.tenants.demo.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.tenants.mariano.url=jdbc:mysql://localhost:3306/mariano?useSSL=false&serverTimezone=UTC
spring.datasource.tenants.mariano.username=mariano
spring.datasource.tenants.mariano.password=marianocs
spring.datasource.tenants.mariano.driver-class-name=com.mysql.cj.jdbc.Driver


server.port=80
server.servlet.context-path=/manorg

logging.config=classpath:log4j2.xml

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload.base-path=D://comoscodinzola//asso-prod//
file.download.base-path=D://comoscodinzola//asso-prod//

path_doc=D://comoscodinzola//asso-prod//
path_firebase=D:/comoscodinzola/asso-prod/firebase/app-comoscodinzola-firebase-adminsdk-fbsvc-7f5afbc64f.json
path_private_assets=c:/temp
path_stemmi=c:/temp
path_report=c:/temp
resize_img_magazzini=12
path_public_assets=c:/temp


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuo.email@gmail.com
spring.mail.password=tuapassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.images.base-url=


